from __future__ import annotations

from dataclasses import dataclass
from textwrap import dedent


@dataclass(slots=True)
class MockProvider:
    """Deterministic fallback used when no real API key is configured."""

    async def chat(self, model: str, messages: list[dict], **kwargs) -> str:
        user_text = "\n".join(str(message.get("content", "")) for message in messages)
        filename = "src/file_swarm/mock_generated.py"
        patch = dedent(
            f"""\
            ## Implementation Summary

            Mock provider produced a safe placeholder patch for model {model}.

            ## Patch

            ```diff
            --- a/{filename}
            +++ b/{filename}
            @@ -0,0 +1,4 @@
            +\"\"\"Generated by file-swarm mock provider.\"\"\"
            +
            +def generated_message() -> str:
            +    return "file-swarm mock run"
            ```

            ## Risk Notes

            This is a fallback implementation for local dry runs.

            ## Suggested Tests

            Add a simple import test for the generated module.

            ## Input Echo

            {user_text[:200]}
            """
        )
        return patch
